name: Production
run-name: Production
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  check-build-and-tests:
    name: Check Development Branch Build & Tests
    uses: ./.github/workflows/build-and-test.yml
    secrets:
      ENV_KEY: ${{ secrets.ENV_KEY }}

  sync-branch:
    name: Syncing Branch
    runs-on: ubuntu-latest
    needs: check-build-and-tests
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
          ref: "main"
      - name: Merge Main Branch to Production
        run: |
          /usr/bin/git config --local user.name azvyae
          /usr/bin/git config --local user.email null
          /usr/bin/git fetch --all
          /usr/bin/git checkout build/production
          /usr/bin/git merge --ff-only main
          /usr/bin/git push origin build/production
